# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e61852760d0bd052364d791dd3381caafdf78747db2850c4ad4d98c73643bb03576f028cfc9466ec6b17c2ae8a7c26ce22caebc10bc3ec48944c9623f6cc0687

test:
  secret_key_base: 3da9d4ba54bac2062b4540714a3818e7c5d8dbd3f30bd1415849051b1b394067fcecafd77eb021549798a5dd8f8f8c61b680a50e965c27c9f972a5fe72d6b447

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
